### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ginkel** [bairhys/prometheus-frigate-exporter#7]
Hi there,

recently the exporter started throwing errors and periodically no longer responds to requests via HTTP:

```
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.11/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/prometheus_client/exposition.py", line 129, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
    for metric in registry.collect():
  File "/usr/lib/python3.11/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/var/python_scripts/prometheus_frigate_exporter.py", line 266, in collect
    self.previous_event_id = events[0]['id']
                             ~~~~~~^^^
```

**Comment by bairhys** [comment]
Hi thanks for letting me know. I was getting this issue too every couple of days or so. Last week I added event counter exporting but I didn't think about when no events are returned. Should be fixed now though, just need to update your image.
